{{- if .Values.deployments }}
{{- range .Values.deployments }}
{{- if .ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dapr_demo.fullname" $ }}-{{ .name }}
  labels:
    {{- include "dapr_demo.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
  {{- with .ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .ingress.tls }}
  tls:
    {{- range .ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "dapr_demo.fullname" $ }}-{{ $.name }}
                port:
                  number: {{ $.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}