{{- if .Values.deployments }}
{{- range .Values.deployments }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dapr_demo.fullname" $ }}-{{ .name }}
  labels:
    {{- include "dapr_demo.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
spec:
  type: {{ .service.type | default $.Values.service.type }}
  ports:
    - port: {{ .service.port | default $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dapr_demo.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ .name }}
{{- end }}
{{- end }}
