provisionDataStore:
  cassandra: false
allInOne:
  enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - jaeger.localhost
    pathType: Prefix

storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
