apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
## FOR LOCAL RUN kafka-pubsub is a REDIS instance =D
  name: kafka-pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""